"""empty message

Revision ID: 1c241c8cdafe
Revises: None
Create Date: 2013-03-19 20:13:20.229893

"""

# revision identifiers, used by Alembic.
revision = '1c241c8cdafe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
